config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'signin', to: 'sessions#new'

  get(
    '/auth/:provider/callback',
    to: 'sessions#create',
    as: :auth_provider_callback
  )

  resources :monsters
  resources :teams

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :sessions, only: [:create]
      resources :monsters, only: [:index, :show, :create, :update, :destroy]
      resources :teams, only: [:index, :show, :create, :update, :destroy]
    end
  end

  root to: 'monsters#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/monster.rb
class Monster < ApplicationRecord
  validates :name, :power, :kind, presence: true

  enum kind: [:fire, :water, :earth, :electric, :wind]

  validates :name, uniqueness: { scope: :user }

  belongs_to :user
  belongs_to :team, required: false

  validate :user_must_match_team_user

  def weakness
    next_kind_index = (Monster.kinds[kind] + 1) % Monster.kinds.size
    Monster.kinds.invert[next_kind_index]
  end

  private

  def user_must_match_team_user
    return true if team.blank? || user == team.user
    errors.add(:user, I18n.t('monster.user_must_match_team_user'))
  end
end

app/models/team.rb
class Team < ApplicationRecord
  belongs_to :user
  has_many :monsters

  validates :name, presence: true, uniqueness: { scope: :user_id }
  validates :monsters, length: { minimum: 0, maximum: 3 }
end

app/models/user.rb
class User < ApplicationRecord
  MONSTER_LIMIT = 20
  TEAM_LIMIT = 3

  has_secure_token

  validates :uid, :provider, presence: true
  validates :uid, uniqueness: { scope: :provider }

  has_many :monsters, dependent: :destroy
  has_many :teams, dependent: :destroy

  validates :monsters, length: { minimum: 0, maximum: MONSTER_LIMIT }
  validates :teams, length: { minimum: 0, maximum: TEAM_LIMIT }
end

app/controllers/api/v1/monsters_controller.rb
module Api
  module V1
    class MonstersController < ApiController
      before_action :find_monster, only: [:show, :update, :destroy]

      def index
        @monsters = UserMonstersQuery.new(current_user).all
      end

      def show
      end

      def create
        @monster = UserMonsterFactory.new(current_user, params: params).build

        if @monster.save
          render @monster
        else
          render json: @monster.errors
        end
      end

      def update
        user_monster_factory = UserMonsterFactory.new(
          current_user, params: params
        )
        if user_monster_factory.update_attributes(@monster)
          render @monster
        else
          render json: @monster.errors
        end
      end

      def destroy
        @monster.destroy
        head :ok
      end

      private

      def find_monster
        @monster = UserMonsterQuery.new(current_user).find(params[:id])
      end
    end
  end
end

app/controllers/api/v1/sessions_controller.rb
module Api
  module V1
    class SessionsController < ApplicationController
      def create
        token = params[:oauth_token]
        facebook_user_info = FacebookUserInfoService.new(token).get

        user = OmniAuthUserFactory.create(
          uid: facebook_user_info['id'],
          provider: 'facebook'
        )

        render json: { token: user.token }
      end
    end
  end
end

app/controllers/api/v1/teams_controller.rb
module Api
  module V1
    class TeamsController < ApiController
      before_action :find_team, only: [:show, :update, :destroy]

      def index
        @teams = UserTeamsQuery.new(current_user).all
      end

      def show
      end

      def create
        @team = UserTeamFactory.new(current_user, params: params).build

        if @team.save
          render @team
        else
          render json: @team.errors
        end
      end

      def update
        user_team_factory = UserTeamFactory.new(current_user, params: params)
        if user_team_factory.update_attributes(@team)
          render @team
        else
          render json: @team.errors
        end
      end

      def destroy
        @team.destroy
        head :ok
      end

      private

      def find_team
        @team = UserTeamQuery.new(current_user).find(params[:id])
      end
    end
  end
end

app/controllers/api_controller.rb
class ApiController < ApplicationController
  before_action :authenticate!

  private

  def authenticate!
    head :unauthorized unless current_user
  end

  def current_user
    token = request.headers['USER-TOKEN']
    return nil if token.blank?
    @current_user ||= User.where(token: token).first
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/monsters_controller.rb
class MonstersController < WebController
  before_action :find_monster, only: [:show, :edit, :update, :destroy]

  def index
    query = UserMonstersQuery.new(current_user, params: params)
    @monsters = query.map do |monster|
      MonsterViewModel.new(monster)
    end
  end

  def show
    @monster = MonsterViewModel.new(@monster)
  end

  def new
    @monster = Monster.new
  end

  def create
    @monster = UserMonsterFactory.new(current_user, params: params).build

    if @monster.save
      flash[:notice] = I18n.t('monster.created')
      redirect_to @monster
    else
      flash.now[:error] = I18n.t('monster.error')
      render :new
    end
  end

  def edit
  end

  def update
    user_monster_factory = UserMonsterFactory.new(current_user, params: params)
    if user_monster_factory.update_attributes(@monster)
      flash[:notice] = I18n.t('monster.updated')
      redirect_to @monster
    else
      flash.now[:eror] = I18n.t('monster.error')
      render :edit
    end
  end

  def destroy
    @monster.destroy
    flash[:notice] = I18n.t('monster.destroyed')
    redirect_to monsters_url
  end

  private

  def find_monster
    @monster = UserMonsterQuery.new(current_user).find(params[:id])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = OmniAuthUserFactory.create(auth_hash)
    session[:user_id] = user.id
    redirect_to root_url
  end

  protected

  def auth_hash
    request.env['omniauth.auth']
  end
end

app/controllers/teams_controller.rb
class TeamsController < WebController
  before_action :find_team, only: [:show, :edit, :update, :destroy]
  before_action :find_monsters, only: [:new, :edit]

  def index
    @teams = UserTeamsQuery.new(current_user).to_a
  end

  def show
  end

  def new
    @team = Team.new
  end

  def create
    @team = UserTeamFactory.new(current_user, params: params).build

    if @team.save
      flash[:notice] = I18n.t('team.created')
      redirect_to @team
    else
      flash.now[:error] = I18n.t('team.error')
      find_monsters
      render :new
    end
  end

  def edit
  end

  def update
    user_team_factory = UserTeamFactory.new(current_user, params: params)
    if user_team_factory.update_attributes(@team)
      flash[:notice] = I18n.t('team.updated')
      redirect_to @team
    else
      flash.now[:eror] = I18n.t('team.error')
      find_monsters
      render :edit
    end
  end

  def destroy
    @team.destroy
    flash[:notice] = I18n.t('team.destroyed')
    redirect_to teams_url
  end

  private

  def find_team
    @team = UserTeamQuery.new(current_user).find(params[:id])
  end

  def find_monsters
    @monsters = UserMonstersQuery.new(current_user, params: params).to_a
  end
end

app/controllers/web_controller.rb
class WebController < ApplicationController
  before_action :authenticate!

  private

  def authenticate!
    redirect_to signin_url unless current_user
  end

  def current_user
    return nil if session[:user_id].blank?
    @current_user ||= User.find(session[:user_id])
  end

  helper_method :current_user
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/monster_helper.rb
module MonsterHelper
  def monster_kinds_for_select
    Monster.kinds.keys.map { |kind| [kind.humanize, kind] }
  end
end

app/helpers/omni_auth_helper.rb
module OmniAuthHelper
  def facebook_login_url
    [
      'https://www.facebook.com/dialog/oauth',
      "?client_id=#{OmniAuth::FACEBOOK_KEY}",
      "&redirect_uri=#{auth_provider_callback_url('facebook')}"
    ].join
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rubymon</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav>
      <%= link_to t('activerecord.models.monster.two'), monsters_url %>
      <%= link_to t('activerecord.models.team.two'), teams_url %>
    </nav>

    <% flash.each do |flash_type, value| %>
      <div data-role="alert" class="<%= flash_type %>">
        <%= value %>
      </div>
    <% end %>

    <main>
      <%= yield %>
    </main>
  </body>
</html>

app/views/monsters/_form.html.erb
<%= form_for monster do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name, required: true %>

  <%= f.label :power %>
  <%= f.text_field :power, required: true %>

  <%= f.label :kind %>
  <%= f.select(
    :kind,
    monster_kinds_for_select,
    { include_blank: true },
    required: true,
  ) %>

  <%= f.submit %>
<% end %>

app/views/monsters/_monsters.html.erb
<% if monsters.present? %>
  <table>
    <thead>
      <tr>
        <th>
          <%= link_to(
            t('activerecord.attributes.monster.name'),
            monsters_url(order: :name)
          ) %>
        </th>
        <th>
          <%= link_to(
            t('activerecord.attributes.monster.power'),
            monsters_url(order: :power)
          ) %>
        </th>
        <th>
          <%= link_to(
            t('activerecord.attributes.monster.kind'),
            monsters_url(order: :kind)
          ) %>
        </th>
        <th>
          <%= link_to(
            t('activerecord.attributes.monster.weakness'),
            monsters_url(order: :kind)
          ) %>
        </th>
        <th colspan="2"></th>
      </tr>
    </thead>
    <tbody>
      <% monsters.each do |monster| %>
        <tr>
          <td><%= link_to monster.name, monster %></td>
          <td><%= monster.power %></td>
          <td><%= monster.kind %></td>
          <td><%= monster.weakness %></td>
          <td>
            <%= link_to t('monster.edit'), edit_monster_url(monster) %>
          </td>
          <td>
            <%=
              link_to(
                t('monster.destroy'),
                monster_url(monster),
                confirm: 'Are you sure?',
                method: :delete
              )
            %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>

app/views/monsters/edit.html.erb
<h1>
  <%= @monster.name %>
</h1>

<%= render 'form', monster: @monster %>

app/views/monsters/index.html.erb
<h1>
  <%= t('activerecord.models.monster.two') %>
</h1>

<% if @monsters.count < User::MONSTER_LIMIT %>
  <%= link_to t('monster.new'), new_monster_url %>
<% end %>

<%= render 'monsters', monsters: @monsters %>

app/views/monsters/new.html.erb
<h1>
  <%= t('monster.new') %>
</h1>

<%= render 'form', monster: @monster %>

app/views/monsters/show.html.erb
<h1>
  <%= @monster.name %>
</h1>

<dl>
  <dt>
    <%= t('activerecord.attributes.monster.name') %>
  </dt>
  <dd>
    <%= @monster.name %>
  </dd>
  <dt>
    <%= t('activerecord.attributes.monster.power') %>
  </dt>
  <dd>
    <%= @monster.power %>
  </dd>
  <dt>
    <%= t('activerecord.attributes.monster.kind') %>
  </dt>
  <dd>
    <%= @monster.kind %>
  </dd>
  <dt>
    <%= t('activerecord.attributes.monster.weakness') %>
  </dt>
  <dd>
    <%= @monster.weakness %>
  </dd>
</dl>

<%= link_to t('monster.edit'), edit_monster_url(@monster) %>
<%= link_to t('monster.destroy'), monster_url(@monster), confirm: 'Are you sure', method: :delete %>